name: Feature_Engineering
max_concurrent_runs: 1
max_retries: 0
tasks:
  - task_key: Feature_Pipeline_FT
    existing_cluster_id: "${CLUSTER_ID}"
    notebook_task:
      notebook_path: "${FEATURE_PIPELINE_PATH_FT}"
      base_parameters:
        env: "${ENV_VARIABLE}"
        task: "FE"

  - task_key: Feature_Pipeline_GT
    existing_cluster_id: "${CLUSTER_ID}"
    notebook_task:
      notebook_path: "${FEATURE_PIPELINE_PATH_GT}"
      base_parameters:
        env: "${ENV_VARIABLE}"
        task: "FE"

  - depends_on:
      - task_key: Feature_Pipeline_GT
      - task_key: Feature_Pipeline_FT
    task_key: Train
    existing_cluster_id: "${CLUSTER_ID}"
    notebook_task:
      notebook_path: "${TRAIN_PATH}"
      base_parameters:
        env: "${ENV_VARIABLE}"
        date_filters: '${DATE_FILTERS}'
        hyperparameters: '${HYPERPARAMETERS}'
        pipeline_id: "${PIPELINE_ID}"
        pipeline_type: "${PIPELINE_TYPE}"
        organization: "${ORGANIZATION}"
        project: "${DEVOPS_PROJECT}"
